name: Deploy ASP.NET Core App to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release -o ./publish

      - name: Clean remote directory
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RASPI_SSH_HOST }}
          username: ${{ secrets.RASPI_SSH_USERNAME }}
          key: ${{ secrets.RASPI_SSH_KEY }}
          script: |
            if [ -d "/home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/aspnetcore-app" ]; then
                rm -rf /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/aspnetcore-app
            fi

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.RASPI_SSH_HOST }}
          username: ${{ secrets.RASPI_SSH_USERNAME }}
          key: ${{ secrets.RASPI_SSH_KEY }}
          source: ./publish/
          target: /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/aspnetcore-app/

      - name: Copy existing appsecrets.json file
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RASPI_SSH_HOST }}
          username: ${{ secrets.RASPI_SSH_USERNAME }}
          key: ${{ secrets.RASPI_SSH_KEY }}
          script: |
            cp /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/appsecrets.json /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/aspnetcore-app/publish/appsecrets.json

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RASPI_SSH_HOST }}
          username: ${{ secrets.RASPI_SSH_USERNAME }}
          key: ${{ secrets.RASPI_SSH_KEY }}
          script: |
            sudo systemctl restart kestrel-aspnetcore-app.service
