name: Deploy ASP.NET Core App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -o ./publish

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.AWS_SSH_HOST }}
        username: ${{ secrets.AWS_SSH_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: ./publish/
        target: /home/${{ secrets.AWS_SSH_USERNAME }}/aspnetcore-app/

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_SSH_HOST }}
        username: ${{ secrets.AWS_SSH_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          sudo systemctl stop kestrel-aspnetcore-app.service
          sudo cp -r /home/${{ secrets.AWS_SSH_USERNAME }}/aspnetcore-app/* /var/www/aspnetcore-app/publish
          sudo systemctl start kestrel-aspnetcore-app.service
